[package]
name = "user_profile_nft"
version = "0.1.0"

[dependencies]
starknet = ">=2.3.0"
openzeppelin = { git = "https://github.com/OpenZeppelin/cairo-contracts.git", tag = "v0.8.0" }

[dev-dependencies]
snforge_std = { git = "https://github.com/foundry-rs/starknet-foundry.git", tag = "v0.10.1" }

[[target.starknet-contract]]
sierra = true
casm = true
